### ISSUE TITLE
ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by cezarlacatus** [hamedpa/ip-info-finder#1]
This error was reporten when the following ip was scanned using the latest 2.0.1 version

IP: 2a02:2f01:f416:b100:dde0:99f0:daa:17a7

```
(node:3052) UnhandledPromiseRejectionWarning: ReferenceError: atob is not defined
    at extractIPInfo (/root/tinly/node_modules/ip-info-finder/modules/ip.js:12:64)
    at sendRequest (/root/tinly/node_modules/ip-info-finder/index.js:36:26)
    at Object.exports.getIPInfo (/root/tinly/node_modules/ip-info-finder/index.js:49:20)
    at processFingerprint (/root/tinly/backend/Socket Worker/redirectionHandlers/trackedRedirect.js:98:39)
    at Socket.<anonymous> (/root/tinly/backend/Socket Worker/redirectionHandlers/trackedRedirect.js:284:7)
    at Socket.emit (events.js:400:28)
    at Socket.emitUntyped (/root/tinly/node_modules/socket.io/dist/typed-events.js:69:22)
    at /root/tinly/node_modules/socket.io/dist/socket.js:465:39
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hamedpa** [comment]
Hi
thanks for reporting issue
this bug existed for node with version lower than 16
you can use latest version 2.0.2 without any problem and this version support older node version
