### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Srini-B** [hamedpa/ip-info-finder#2]
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /Users/cyron/Documents/BeeBox/sandclock/release/app/node_modules/ip-info-finder/modules/currency.js:8:53
    at Array.forEach (<anonymous>)
    at getCurrencyDetail (/Users/cyron/Documents/BeeBox/sandclock/release/app/node_modules/ip-info-finder/modules/currency.js:7:14)
    at AsyncFunction.exports.getIPInfo.currency (/Users/cyron/Documents/BeeBox/sandclock/release/app/node_modules/ip-info-finder/index.js:55:31)

**Comment by hamedpa** [comment]
hello
you can use newest version 2.0.3 and the bug fixed on this version
thanks for reporting.
